import { Button, Card } from "@heroui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <main className="grid place-items-center h-screen">
        <Card className="p-5 flex flex-col gap-4">
          hello world
          <Button>let's go</Button>
        </Card>
      </main>
    </>
  );
}
